export const gameList = [ {
  title: "Age of Dragons",
  coinSymbol: "$AOD",
  bgImage: '/images/games/aod.png',
  video: '/videos/web_aod.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/aod.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Age of Dragons is an unreal engine medieval metaverse inspired by Game of Thrones. Own land, castles, forts, fire dragons, ice dragons and more. Explore the world and hunt down dragon eggs to breed your own dragons. Battle an army of ice zombies to earn rewards.",
  websiteLink: "http://ageofdragons.io/",
  twitterLink: "https://twitter.com/ageof_dragons",
  coinLink: "#",
}, {
  title: "Block Football Manager",
  coinSymbol: "$FOOTBALL",
  bgImage: '/images/games/bfm.png',
  video: '/videos/web_bfm.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/bfm.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "It will be the first football manager game on the blockchain. You can own players, stadiums and stake players to train. New players wil emerge based on the blockchain hash making them unique. Win leagues, competitions and become the best manager in the block.",
  websiteLink: "http://blockfootball.io/",
  twitterLink: "https://twitter.com/block_football",
  coinLink: "#",
}, {
  title: "X-Speed",
  coinSymbol: "$SPEED",
  bgImage: '/images/games/xspeed.png',
  video: '/videos/web_xspeed.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/xspeed.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "X-Speed is play to earn super car racing game on the Polygon ecosystem. Players can own cars, drivers, and a share of metaverse racing tracks for passive income. All cars will be upgradable via NFTs parts such as engines, exhausts, spoilers and tyres. There will be a range of drivers and their natural skills can be enhanced by staking rewards. Exciting race modes in highly immersive environments will test your skills to the limit in either PvP or PvE.",
  websiteLink: "#",
  twitterLink: "https://twitter.com/XSpeed_Racers",
  coinLink: "#",
}, {
  title: "Meta-x",
  coinSymbol: "$METAX",
  bgImage: '/images/games/metax.jpg',
  video: '/videos/web_metax.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/metax.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "A metaverse created using unreal engine 5. There will be 9 sectors surrounding a central core where Meta-X HQ will be located. Sectors include Gaming, Art, Shopping, Education, Escape, Business Stytopia, Entertainment and Connect. The expansive metaverse will serve the need for all types of interactions and will be a future cornerstone of the MetaXSeed ecosystem.",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_MetaverseX",
  coinLink: "#",
}, {
  title: "X-SPACE",
  coinSymbol: "$XSPC",
  bgImage: '/images/games/xspace.jpg',
  video: '/videos/web_xspace.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/metax.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "A metaverse created using unreal engine 5. There will be 9 sectors surrounding a central core where Meta-X HQ will be located. Sectors include Gaming, Art, Shopping, Education, Escape, Business Stytopia, Entertainment and Connect. The expansive metaverse will serve the need for all types of interactions and will be a future cornerstone of the MetaXSeed ecosystem.",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_MetaverseX",
  coinLink: "#",
}, {
  title: "Odin's Ring",
  coinSymbol: "$ODIN",
  bgImage: '/images/games/odin.png',
  video: '/videos/web_odin.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/odin.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Odin's Ring is a game based on the 9 worlds of norse mythology. This isometric style play to earn game will contain a fusion of popular JPRG and MOBA game mechanics. Asgard and Midgard is under attack, help the gods defend and ward off invaders. Players can explore fictitious worlds, fight mythical creatures and harvest rare materials. Enhance your experience with playable NFT characters and accessories which all contribute toward a comprehensive upgrade and levelling system Valhalla awaits..",
  websiteLink: "#",
  twitterLink: "https://twitter.com/Odins_Ring",
  coinLink: "#",
}, {
  title: "Chain Ski",
  coinSymbol: "$SKI",
  bgImage: '/images/games/chainski.png',
  video: '/videos/web_chainski.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/chainski.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Chain Ski is a VR ski-as-you-earn & free-to-play ski resort within Netvrk entertainment district. Own skiers, upgradable equipment and put on your haptic wearables to try the down hill or x-country challenges. You can also just explore the ski resort. Share of the advertising revenue will be redistributed to the token holders",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_chainski",
  coinLink: "#",
}, {
  title: "Opsat",
  coinSymbol: "$OPSAT",
  bgImage: '/images/games/opsat.png',
  video: '/videos/web_opsat.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/chainski.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Chain Ski is a VR ski-as-you-earn & free-to-play ski resort within Netvrk entertainment district. Own skiers, upgradable equipment and put on your haptic wearables to try the down hill or x-country challenges. You can also just explore the ski resort. Share of the advertising revenue will be redistributed to the token holders",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_chainski",
  coinLink: "#",
}, {
  title: "Defi Gravity",
  coinSymbol: "$DEFI",
  bgImage: '/images/games/DefiGravity.png',
  video: '/videos/web_defi_gravity.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/chainski.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Chain Ski is a VR ski-as-you-earn & free-to-play ski resort within Netvrk entertainment district. Own skiers, upgradable equipment and put on your haptic wearables to try the down hill or x-country challenges. You can also just explore the ski resort. Share of the advertising revenue will be redistributed to the token holders",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_chainski",
  coinLink: "#",
}, {
  title: "Music Beatz",
  coinSymbol: "$MBT",
  bgImage: '/images/games/music beatz.jpg',
  video: '/videos/web_music_beatz.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/chainski.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Chain Ski is a VR ski-as-you-earn & free-to-play ski resort within Netvrk entertainment district. Own skiers, upgradable equipment and put on your haptic wearables to try the down hill or x-country challenges. You can also just explore the ski resort. Share of the advertising revenue will be redistributed to the token holders",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_chainski",
  coinLink: "#",
}, {
  title: "X-FIGHTER",
  coinSymbol: "$XFT",
  bgImage: '/images/games/x fighter.jpg',
  video: '/videos/web_xfighter.mp4',
  width: 596, height: 843, 
  coinImage: '/images/coins/chainski.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Chain Ski is a VR ski-as-you-earn & free-to-play ski resort within Netvrk entertainment district. Own skiers, upgradable equipment and put on your haptic wearables to try the down hill or x-country challenges. You can also just explore the ski resort. Share of the advertising revenue will be redistributed to the token holders",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_chainski",
  coinLink: "#",
}, {
  title: "SHOOTER RUN",
  coinSymbol: "$STR",
  bgImage: '/images/games/shoot or run v2.png',
  video: '/videos/web_shooter_run.m4v',
  width: 596, height: 843, 
  coinImage: '/images/coins/chainski.png',
  chainImage: '/images/polygon.svg',
  status: "upcomming",
  context: "Chain Ski is a VR ski-as-you-earn & free-to-play ski resort within Netvrk entertainment district. Own skiers, upgradable equipment and put on your haptic wearables to try the down hill or x-country challenges. You can also just explore the ski resort. Share of the advertising revenue will be redistributed to the token holders",
  websiteLink: "#",
  twitterLink: "https://twitter.com/_chainski",
  coinLink: "#",
}];