export const teamList = [ {
    name: "Shipon Chowdhury",
    role: "CEO & Co-Founder",
    content: "Finance & Technology Specialist. 20+ years experience within computing, finance and project management. working with industry leading companies and investments banks. Investor in many upcoming metaverse projects such as NetVrk and Bloktopia. Avid gamer from a young age. Favourite All Time Games are Mortal Kombat, Command and Conquer, Pro Evolution Soccer, Neptunes Pride and Fortnite.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "http://www.linkedin.com/in/shipon-chowdhury-1a669118",
    avatar: "/images/team/shipon.jpg",
}, {
    name: "Max Krawiec",
    role: "CTO",
    content: "Phantom UI/UX Currently working for Phantom. Long term experience in the crypto space mining ethereum and other coins. Specifically focused on play 2 earn and game development using unreal engine and blender.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/max-krawiec-05988814/",
    avatar: "/images/team/max.png",
}, {
    name: "Amjad Chowdhury",
    role: "COO",
    content: "Operational & Programme Management Over 10+ years experience with in retail sector & 7+ years in operation management. Responsible for all internal employees to ensure that they are motivated and trained and carry out their responsibilities to the required standard. Contributes to the strategic direction to ensure that the company achieves its short and long-term objectives.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/amjad-chowdhury-463120161/",
    avatar: "/images/team/amjad1.png",
}, {
    name: "Dhruti Dattani",
    role: "CMO",
    content: "Campaign Manager Specialist. 7+ years experience in campaign management. Managing advertising revenues for many well know companies across the global. Dhruti is responsible for the marketing budget and will managing marketing campaigns and the direction",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/dhruti-dattani-2617191a/",
    avatar: "/images/team/dhruti.png",
}, {
    name: "Nik Lalji",
    role: "Art Director",
    content: "Experienced Art Director and Artist. Nik is responsible for the visual style of the animation and game illustrations. He has come from a data privacy background which will help keep information secure. Nik will drive the creative ideas and direction",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/nik-lalji-cfe-b15ab7107/",
    avatar: "/images/team/nik.png",
}, {
    name: "David Leiva",
    role: "Senior Blockchain Developer",
    content: "Experienced Cardano, Solana & Ethereum Blockchain Developer. Design and build a smart contracts architecture, incentives structure, yield pools and strategies. Design, implement and test smart contract upgrades and additions. Work with smart contract auditors to implement fixes.",
    websiteLink: "https://davidleiva.me",
    twitterLink: "https://twitter.com/CryptoSpider8",
    githubLink: "https://github.com/c-spider",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/david-leiva-46a619248/",
    avatar: "/images/team/david.png",
}, {
    name: "Asif Mahmood",
    role: "Blockchain Architect",
    content: "Experience in cutting edge blockchain networks providing functions of persistence store and trusted network for funds transfers. Architecture of underlying application comprised of a microservices based application with clearly defined domain boundaries. Experience with 'Proof of Authority' blockchain algorithm.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/asif-mahmood/",
    avatar: "/images/team/Asif.png",
}, {
    name: "Gustavo Rodrigues",
    role: "Senior Frontend Developer",
    content: "Gustavo is an experienced frontend developer who has worked on interactive websites, apps and games.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/gugateider/",
    avatar: "/images/team/gustavo.png",
}, {
    name: "David Mola",
    role: "Frontend Developer",
    content: "David is an experienced frontend developer who has worked on building websites and launchpads.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "",
    avatar: "/images/team/david mola.png",
}, {
    name: "Anish Saini",
    role: "Unreal Level Developer",
    content: "Professional level designer/environment artist in unreal 4 and 5 and cinematic artist. Over 4 years experience.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "",
    avatar: "/images/team/Anish.png",
}, {
    name: "Efe Toker",
    role: "Frontend Developer",
    content: "Frontend Web Developer with 5 years experience. Experience in React, Angular and PHP.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/efetoker/",
    avatar: "/images/team/efe.png",
}, {
    name: "Gautam Roy",
    role: "Growth Manager",
    content: "Gautam is skilled at scaling projects from inception to operation and actively nurtured over 20 projects to date. He will enable MetaXSeed to accelerate and advocates strategic partnerships through his roster of connections in the crypto industry. Having him onboard will significantly help to improve our chances of reaching our goals and significantly strengthen our team.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "",
    avatar: "/images/team/gautam.jpg",
}, {
    name: "Garibaldy Mukti",
    role: "Chief Game Designer",
    content: "Founder and CEO of the highly successful Night Spade Games Studio. Highly experienced and talented games designer and developer. Fifteen years in the gaming industry working with some of the leading brands in the world such as Google, Microsoft, Nickeloden and Danone. Gerry will be heading up the Unity division and manage co-ordination of our Asian development teams.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/garibaldymukti/",
    avatar: "/images/team/gerry.png",
}, {
    name: "Sundeep Siripurapu",
    role: "Advisor - TrustSwap",
    content: "Core Team Member of TrustSwap. Designed tokenomics for various projects and/or serving as a strategic advisor/consultant for over 20+ projects encompassing DeFi, GameFi and Layer-1 protocols. Sundeep can accelerate fundraising along with strategic partnerships through his network of connections.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/sundeep-krishna-siripurapu-95575862/",
    avatar: "/images/team/sandeep.png",
}
, {
    name: "Nathan Christian",
    role: "Strategic Advisor - CEO of LedgerScore",
    content: "Nathan is the Founder and CEO of LedgerScore. A top-rated global influencer in Blockchain and Fintech. Nathan’s a technical expert in blockchain-based accounting and financial applications. An active angel investor and serial entrepreneur with contributions to 40+ technology start-ups",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/nathan-christian-90365414a/",
    avatar: "/images/team/nathan.png",
}, {
    name: "J Edwardsc",
    role: "Advisor - 316VC Founder",
    content: "Coming from a background in trading stocks, derivatives and options, John transitioned into crypto 9 years ago as an early Crypto investor. He now spends much time hunting down and nurturing early stage crypto investments.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/john-edwards-ab12871a/",
    avatar: "/images/team/john1.png",
}, {
    name: "Rico Richardson",
    role: "Media Communication Specialist",
    content: "Rico is a Crypto Youtuber that has many years of experience in the financial industry and presents newly launched projects to the public in an educational and entertaining way. He loves to play games and is a blockchain enthusiast.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "",
    avatar: "/images/team/rico1.png",
}, {
    name: "Jose Fernando Molina Pinos",
    role: "Spanish and South American Representative",
    content: "CEO of Territoriobitcoin. Spanish media coordinator ensuring the blockchain is understood by the spanish audience. Organizes annual blockchain conferences and is a very well connected member of the spanish crypto community.",
    websiteLink: "",
    twitterLink: "",
    githubLink: "",
    instagramLink: "",
    linkedinLink: "https://www.linkedin.com/in/fernandomolinapinos/",
    avatar: "/images/team/fernando.png",
}];